apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: checkoutservice-cpu-stress
  namespace: boutique
spec:
  selector:
    pods:
      boutique:
        - checkoutservice-5d9d84cd44-qk566
  mode: one
  stressors:
    cpu:
      workers: 2
      load: 90
  duration: '300s'  # 5分钟
