apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: cartservice-mem-stress
  namespace: boutique
spec:
  selector:
    pods:
      boutique:
        - cartservice-7d76bb9df-98kft 
  mode: one
  stressors:
    memory:
      workers: 1
      size: '500M'
  duration: '300s'  # 10分钟
